spring.application.name=batch-processing

spring.datasource.url=jdbc:postgresql://postgresdb:5432/productsdb
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.table-prefix=BATCH_

server.port=8080

management.endpoints.web.exposure.include=beans,env,health,info,metrics,mappings,prometheus
management.endpoint.health.show-details=always
management.health.probes.enabled=true

logging.level.com.example.batchprocessing=DEBUG
